schema:
  - ./schema/schema.graphql
model:
  filename: ./model/models_gen.go
autobind:
  - github.com/Yamashou/gqlgenc/example/autobind/model
client:
  filename: ./gen/client.go
models:
  DateTime:
    model: github.com/99designs/gqlgen/graphql.Time
query:
  - "./query/*.graphql"
generate:
  clientV2: true
  clientInterfaceName: "GithubGraphQLClient"
  query: false
  mutation: false
