schema:
  - ./schema/schema.graphql
model:
  filename: ./model/models_gen.go
client:
  filename: ./gen/client.go
models:
  EnumTyped:
    model: ./model.EnumTyped
    enum_values:
      ONE:
        value: ./model.EnumTypedOne
      TWO:
        value: ./model.EnumTypedTwo
  EnumUntyped:
    model: github.com/99designs/gqlgen/graphql.Int
    enum_values:
      ONE:
        value: ./model.EnumUntypedOne
      TWO:
        value: ./model.EnumUntypedTwo
query:
  - "./query/*.graphql"
generate:
  clientInterfaceName: "GithubGraphQLClient"
